### ISSUE TITLE
TypingError: cannot determine Numba type of <class 'object'>

### ISSUE THREAD

**Issue by msilva913** [EconForge/dolo#159]
[Shopping time and net product creation.txt](https://github.com/EconForge/dolo/files/3404596/Shopping.time.and.net.product.creation.txt)

Greetings:

For some reason, when I try to import the YAML file, I obtain a Numba type inference error. I have checked that each parameter is defined in the calibration and that there are no additional parameters.

I am running Python 3.6.2 on Windows 10, dolo version 0.4.9.9. I attach a txt file with the YAML code.

Thank you.

**Comment by albop** [comment]
can you copy the error you get ? If I try to import your model I get: `Error while parsing YAML file. Probable syntax error in your model file :  Shopping.time.and.net.product.creation.txt`. From a quick inspection at the file it looks like there is a lonely "parameters" word in the calibration section, which really should be a comment.

**Comment by msilva913** [comment]
Hi Pablo:

Yes, there was a lonely "parameters" word. However, commenting it out does not remove the exception.

The error is
 TypingError: cannot determine Numba type of <class 'object'>
and the full Traceback is

model = yaml_import("shopping_home_production_vcu_7172019.yaml")
Traceback (most recent call last):

  File "<ipython-input-107-fcc7801eca80>", line 1, in <module>
    model = yaml_import("shopping_home_production_vcu_7172019.yaml")

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\dolo\compiler\model_import.py", line 28, in yaml_import
    return Model(data)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\dolo\compiler\model.py", line 278, in __init__
    self.__compile_functions__()

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\dolo\compiler\model.py", line 331, in __compile_functions__
    fff, vectorize=True, debug=debug)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\dolang\function_compiler.py", line 80, in make_method_from_factory
    [fty], signature, target='parallel', nopython=True)(fun)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 179, in wrap
    guvec.add(fty)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 198, in add
    self.nb_func, targetoptions, sig)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 129, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 78, in compile
    return self._compile_core(sig, flags, locals)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 113, in _compile_core
    flags=flags, locals=locals)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 360, in compile_extra
    return self._compile_bytecode()

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 722, in _compile_bytecode
    return self._compile_core()

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 709, in _compile_core
    res = pm.run(self.status)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 246, in run
    raise patched_exception

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 238, in run
    stage()

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 452, in stage_nopython_frontend
    self.locals)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\compiler.py", line 864, in type_inference_stage
    infer.build_constraint()

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\typeinfer.py", line 800, in build_constraint
    self.constrain_statement(inst)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\typeinfer.py", line 959, in constrain_statement
    self.typeof_assign(inst)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1021, in typeof_assign
    self.typeof_global(inst, inst.target, value)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1117, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)

  File "C:\Users\TJSEM\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1040, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)

Regards,
Mario

**Comment by msilva913** [comment]
Hi Pablo:

I do not suppose there are any leads on the issue? Clearly, numba cannot infer the types of one of the variables, but I cannot identify the issue in the YAML file. I am working on writing an Euler-equation based fixed point iteration for solving the model, but it would really be nice to get it to work on dolo, which has an elegant and efficient interface.

Best

**Comment by albop** [comment]
hmm, I just tried it again, the model seems to import just fine. there is no guarantee it will solve though
